name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s 'bleeding'
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Install MoonBit (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $env:MOONBIT_INSTALL_VERSION = "bleeding"
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Inspect MoonBit version
        run: |
          moon version --all

      - name: Update mooncakes.io index
        run: moon update

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run tests
        run: |
          moon check --target native
          moon test --target native
